# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aea0b8cd350bd3ce19e15090fb199840c0974b39ce0c58f4044bc3ec029e9f25b69d4b7fc1bd2e97e2f7a6badea6597ec195233cdddff0462645333705afc64
  auth0_domain: https://iluvu.auth0.com/
  auth0_api_audience: http://zw-api.zencephalon.com/

test:
  secret_key_base: 16ebc9475b63dfeb6d36442994398d5fa4a9491931dce78fd94e84ade7c766979ea67096e78c19bb5095c4ebdd1394c1a6a341bca3179693e32b13a95501a35a
  auth0_domain: https://iluvu.auth0.com/
  auth0_api_audience: http://zw-api.zencephalon.com/

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_domain: https://iluvu.auth0.com/
  auth0_api_audience: http://zw-api.zencephalon.com/
